### ISSUE TITLE
Match state in a different file

### ISSUE THREAD

**Issue by ceelogre** [habbes/ussd-menu-builder#16]
I'm having a hard time keeping different states into modules, the exact problem is to match a state when it's in a different file.

**main.js**
```javascript
menu.state('welcome', {  
  run: () => {    
    menu.con('1. Hospital services')
  },
  next: {
    '1': 'hospital.js' // How can I do this?
  }
}
```
**hospital.js**
```js
menu.state('register', {
run : () => {
    ...
}
```

**Comment by habbes** [comment]
@ceelogre one way to achieve that is to pass the menu instance  as an argument to the different modules, e.g.

**main.js**

```
const hospitalStates = require('./hospital.js');

menu.state('welcome', {  
  run: () => {    
    menu.con('1. Hospital services')
  },
  next: {
    '1': 'register' // defined in hospital.js
  }
});

// add hospital routes
hospitalStates(menu);
```

**hospital.js**

```js
module.exports = function hospitalStates(menu) {
  menu.state('register', {
    run: () => {
      // ...
    }
  });

}
```

**Comment by habbes** [comment]
In retrospect I'm not to happy about this design where the `hospitalStates` function mutates the `menu` instance it receives as argument, but I'm not sure whether there's a cleaner way to modularise the menus.

**Comment by ceelogre** [comment]
Thanks, now that makes me wonder in the Feature section (README), you mention that the state-based approach allows modularizing complex menus in different files. What approach were you having in mind exactly? That could help me change my design, maybe.

**Comment by yono38** [comment]
He @ceelogre I have my states split across files (different menu flows) that are all pulled into a single index file. I can demostrate below:

**index.ts**:
```
import getPayPolicyFlow from './payPolicy';
import getClaimPayoutFlow from './claimPayout';
import getCheckPolicyFlow from './checkPolicy';

const getAppSteps = (opts?: UssdMenu.UssdMenuOptions): UssdMenu => {
    const menu = new UssdMenu(opts);

    menu.startState({
        run: async () => {
              ...
        },
        next: { ... },
    });
    ... 

    // Note that I return the menu in the function but don't need to use it since
    getPayPolicyFlow(menu);
    getClaimPayoutFlow(menu);
    getCheckPolicyFlow(menu);
    ...

    return menu;
});

export default getAppSteps;
```

Then in each of the files I have a default export like so:

**payPolicy.ts**:

```
const getPayPolicyFlow = (menu: UssdMenu): UssdMenu => {
    menu.state('payPolicy.policySelect', { ... });

    ... other states

    return menu;
});

export default getPayPolicyFlow;
```

I then pull the `getAppSteps` function into my express app:

**app.ts**:

```
app.post('/ussd', function(req, res) {
  const menu = getAppSteps();

  // Note: this is also where I initialize my session, but I've excluded that code for the example

  menu.run(req.body, (ussdResult: string) => {
      res.send(ussdResult);
  });
});
```

In this way I am able to keep all the modules separated but pull them into the `getAppSteps` function at the end. Due to the way that `ussd-menu-builder` works (iterating through all app steps and pulling them into a key-value object before parsing the request, you are able to reference any state in any of the modules and it will be able to use it (just be careful to only declare each state once! I use namespacing for that)

**Comment by ceelogre** [comment]
I had never thought about such an approach, this comment is very enlightening!! I'll go through it again to see if I can build something like that.
